on:
  workflow_dispatch:
    inputs:
      filter_repos:
        description: "Redemption198/nurnet-plus,Redemption198/youtube-ambient-mode"
        required: false

      filter_secrets:
        description: "REPO_ACCESS"
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Sync secrets
        uses: xt0rted/secrets-sync@v1
        with:
          repo_token: ${{ secrets.REPO_ACCESS }}
          filter_repos: ${{ github.event.inputs.filter_repos }}
          filter_secrets: ${{ github.event.inputs.filter_secrets }}
        env:
          REPO_ACCESS: ${{ secrets.REPO_ACCESS }}